# Generated by Django 3.1.2 on 2021-07-01 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class_level', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=15)),
                ('background', models.CharField(max_length=15)),
                ('alignment', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=20)),
                ('xp', models.IntegerField()),
                ('str', models.IntegerField()),
                ('dex', models.IntegerField()),
                ('con', models.IntegerField()),
                ('int', models.IntegerField()),
                ('wis', models.IntegerField()),
                ('cha', models.IntegerField()),
                ('str_save', models.IntegerField()),
                ('dex_save', models.IntegerField()),
                ('con_save', models.IntegerField()),
                ('int_save', models.IntegerField()),
                ('wis_save', models.IntegerField()),
                ('cha_save', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('init', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('hp', models.CharField(max_length=9)),
                ('hp_temp', models.IntegerField()),
                ('portrait', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
