# Generated by Django 3.1.2 on 2021-07-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
