# Generated by Django 3.1.2 on 2021-09-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20210701_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portraits'),
        ),
    ]
