# Generated by Django 3.1.2 on 2021-09-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20210927_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(upload_to='portraits'),
        ),
    ]
