# Generated by Django 3.1.2 on 2021-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20210927_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(upload_to='RpgSheet/media/portraits/'),
        ),
    ]
